# Generated by Django 5.2.1 on 2025-05-16 13:28

import django.db.models.deletion
import mixins.str_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Foto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.BinaryField()),
            ],
            bases=(mixins.str_mixin.StrMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_view",
                    models.SmallIntegerField(
                        choices=[(0, "Видимое событие"), (1, "Скрытое событие")]
                    ),
                ),
                (
                    "event_type",
                    models.SmallIntegerField(
                        choices=[(0, "выполненное событие"), (1, "будущее событие")]
                    ),
                ),
                ("event_year", models.IntegerField()),
                ("event_date1", models.DateField()),
                ("event_date2", models.DateField()),
                ("event_name", models.CharField(max_length=255)),
                ("event_description", models.TextField()),
                ("event_video", models.URLField(blank=True)),
                ("event_album", models.URLField(blank=True)),
                ("event_route", models.URLField(blank=True)),
                ("event_report", models.TextField(blank=True)),
                (
                    "event_foto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="running.foto",
                    ),
                ),
            ],
            bases=(mixins.str_mixin.StrMixin, models.Model),
        ),
    ]
