# Generated by Django 5.2.1 on 2025-05-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("running", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foto",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
