# Generated by Django 5.2.1 on 2025-05-16 22:05

import django.db.models.deletion
import mixins.str_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("running", "0002_alter_foto_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=110,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
            ],
            bases=(mixins.str_mixin.StrMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_album",
            field=models.URLField(blank=True, verbose_name="Ссылка на фотоальбом"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date1",
            field=models.DateField(verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date2",
            field=models.DateField(verbose_name="Дата конца"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_description",
            field=models.TextField(verbose_name="Описания события"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_foto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="running.foto",
                verbose_name="Изображения события",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_name",
            field=models.CharField(max_length=255, verbose_name="Названия события"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_report",
            field=models.TextField(blank=True, verbose_name="Отчет события"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_route",
            field=models.URLField(blank=True, verbose_name="Ссылка на маршрут"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.SmallIntegerField(
                choices=[(0, "выполненное событие"), (1, "будущее событие")],
                verbose_name="Тип события",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_video",
            field=models.URLField(blank=True, verbose_name="Ссылка на видео"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_view",
            field=models.SmallIntegerField(
                choices=[(0, "Видимое событие"), (1, "Скрытое событие")],
                verbose_name="Видимость события",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_year",
            field=models.IntegerField(verbose_name="Год события"),
        ),
        migrations.AlterField(
            model_name="foto",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Изображения"),
        ),
        migrations.AlterField(
            model_name="foto",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название изображения"),
        ),
    ]
