# Generated by Django 5.2.1 on 2025-05-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("running", "0003_feedback_alter_event_event_album_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Событие", "verbose_name_plural": "События"},
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратная связь",
            },
        ),
        migrations.AlterModelOptions(
            name="foto",
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date1",
            field=models.DateField(blank=True, verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date2",
            field=models.DateField(blank=True, verbose_name="Дата конца"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_description",
            field=models.TextField(blank=True, verbose_name="Описания события"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Названия события"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.SmallIntegerField(
                choices=[(0, "события"), (1, "проекты")], verbose_name="Тип события"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Год события"
            ),
        ),
    ]
