# Generated by Django 5.2.1 on 2025-05-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("running", "0004_alter_event_options_alter_feedback_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_album",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на фотоальбом"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date1",
            field=models.DateField(blank=True, null=True, verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date2",
            field=models.DateField(blank=True, null=True, verbose_name="Дата конца"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описания события"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Названия события"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_report",
            field=models.TextField(blank=True, null=True, verbose_name="Отчет события"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_route",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на маршрут"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(0, "события"), (1, "проекты")],
                null=True,
                verbose_name="Тип события",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_video",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на видео"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_view",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(0, "Видимое событие"), (1, "Скрытое событие")],
                null=True,
                verbose_name="Видимость события",
            ),
        ),
    ]
