# Generated by Django 5.2.1 on 2025-05-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("running", "0005_alter_event_event_album_alter_event_event_date1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_route",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Ссылка на маршрут"
            ),
        ),
    ]
